#pragma once
#include "pch.h"

enum class TEXT_COLOR_TYPE
{
	BLACK = 0,
	GRAY = FOREGROUND_INTENSITY,
	RED = FOREGROUND_RED,
	RED_INENSITY = FOREGROUND_RED | FOREGROUND_INTENSITY,
	ORANGE = FOREGROUND_RED | FOREGROUND_GREEN,
	ORANGE_INENSITY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	GREEN = FOREGROUND_GREEN,
	GREEN_INENSITY = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	SKY = FOREGROUND_GREEN | FOREGROUND_BLUE,
	SKY_INENSITY = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	BLUE = FOREGROUND_BLUE,
	BLUE_INENSITY = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	PURPLE = FOREGROUND_BLUE | FOREGROUND_RED,
	PURPLE_INENSITY = FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY,

	WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,

	END
};

enum class BACKGROUND_COLOR_TYPE
{
	BLACK = 0,
	GRAY = BACKGROUND_INTENSITY,
	RED = BACKGROUND_RED,
	RED_INENSITY = BACKGROUND_RED | BACKGROUND_INTENSITY,
	ORANGE = BACKGROUND_RED | BACKGROUND_GREEN,
	ORANGE_INENSITY = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	GREEN = BACKGROUND_GREEN,
	GREEN_INENSITY = BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	SKY = BACKGROUND_GREEN | BACKGROUND_BLUE,
	SKY_INENSITY = BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
	BLUE = BACKGROUND_BLUE,
	BLUE_INENSITY = BACKGROUND_BLUE | BACKGROUND_INTENSITY,
	PURPLE = BACKGROUND_BLUE | BACKGROUND_RED,
	PURPLE_INENSITY = BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY,

	WHITE = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,

	END
};

enum class LAYOUT_TYPE
{
	TITLE,
	STAT,
	MAP,
	STORY,
	SELECT,

	END
};